-- ============================================================================
-- Importação dos contratos públicos ativos (extraídos do pipeline em 18/06/2026).
-- Rode no SQL Editor do Supabase. Idempotente (ON CONFLICT DO NOTHING).
-- Todos entram como status 'ativo'; os de vigência expirada pelo documento
-- aparecerão em VERMELHO na coluna Ativos (alerta de renovação).
-- Anexos vazios e links nulos — os PDFs do ZIP não têm URL pública; anexe pelo card.
-- ============================================================================

insert into public.contratos (id, data) values
('ct-imp-mandirituba', '{"id": "ct-imp-mandirituba", "cidade": "Mandirituba", "uf": "PR", "titulo": "Prefeitura de Mandirituba — Credenciamento Médico UBS e PA", "tipoServico": "Serviços médicos — clínico geral e plantonista (Policlínica/Hospital Municipal/UPA) · Contrato 068/2025", "inicio": "2025-07-11", "fimVencimento": "2026-01-11", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Ana Elisa P. do Amaral Vilczeki / Andrieli Tais Zimerman", "telefone": "(41) 3626-1122", "email": "contratos@mandirituba.pr.gov.br"}, "anexos": [], "valor": 73489.2}'::jsonb),
('ct-imp-camboriu', '{"id": "ct-imp-camboriu", "cidade": "Camboriú", "uf": "SC", "titulo": "Prefeitura de Camboriú — Credenciamento Médico UBS", "tipoServico": "Consultas médicas em clínica geral (UBS) · Contrato 074/2022 (4º aditivo)", "inicio": "2025-10-20", "fimVencimento": "2026-10-19", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Alexandre F. Kons dos Santos / Felipe O. Dias da Rocha", "telefone": "(47) 3365-9500", "email": "ouvidoria@cidadedecamboriu.sc.gov.br"}, "anexos": [], "valor": 318750.0}'::jsonb),
('ct-imp-monte-alegre', '{"id": "ct-imp-monte-alegre", "cidade": "Monte Alegre dos Campos", "uf": "RS", "titulo": "Prefeitura de Monte Alegre dos Campos", "tipoServico": "Médico clínico geral 40h/sem (UBS) · Contrato 201/2023 (2º aditivo)", "inicio": "2025-11-13", "fimVencimento": "2026-11-12", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Onilton João Capelini", "telefone": "(54) 3908-3700", "email": "assessoriagabinete.mac@gmail.com"}, "anexos": [], "valor": 253039.08}'::jsonb),
('ct-imp-chapeco', '{"id": "ct-imp-chapeco", "cidade": "Chapecó", "uf": "SC", "titulo": "Prefeitura de Chapecó — Neuropediatria (telemedicina)", "tipoServico": "Neuropediatria por teleatendimento · Contrato 121/2023-FMS (1º aditivo)", "inicio": "2024-10-16", "fimVencimento": "2025-10-16", "modalidade": "online", "status": "ativo", "contato": {"nome": "João Lenz Neto", "email": "contratocentral@chapeco.sc.gov.br"}, "anexos": [], "valor": 360000.0}'::jsonb),
('ct-imp-ipiranga', '{"id": "ct-imp-ipiranga", "cidade": "Ipiranga", "uf": "PR", "titulo": "Prefeitura de Ipiranga", "tipoServico": "Clínica geral 40h/sem (ESF) · Contrato 274/2023 (14º aditivo)", "inicio": "2025-11-01", "fimVencimento": "2026-05-01", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Douglas Davi Cruz", "telefone": "(42) 3242-8501"}, "anexos": [], "valor": 268800.0}'::jsonb),
('ct-imp-sesi-sjp', '{"id": "ct-imp-sesi-sjp", "cidade": "São José dos Pinhais", "uf": "PR", "titulo": "SESI São José dos Pinhais — Médico Examinador", "tipoServico": "Saúde ocupacional — consulta ocupacional e hora técnica clínico geral · TC 040/2025", "inicio": "2025-01-26", "fimVencimento": "2026-01-26", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Fabio José dos Santos", "telefone": "(41) 3271-9000", "email": "fabio.santos@sistemafiep.org.br"}, "anexos": []}'::jsonb),
('ct-imp-sjp-1', '{"id": "ct-imp-sjp-1", "cidade": "São José dos Pinhais", "uf": "PR", "titulo": "São José dos Pinhais — UPA Afonso Pena (contrato original)", "tipoServico": "Clínico geral — UPA Afonso Pena · Contrato 419/2023", "inicio": "2023-11-24", "fimVencimento": "2024-02-24", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Vicente Henrique Sansana / Isabela Marçal Salomé", "telefone": "(41) 3381-6800"}, "anexos": [], "valor": 151362.0}'::jsonb),
('ct-imp-sjp-2', '{"id": "ct-imp-sjp-2", "cidade": "São José dos Pinhais", "uf": "PR", "titulo": "São José dos Pinhais — UPA Afonso Pena (aditivos)", "tipoServico": "Clínico geral — UPA Afonso Pena · Contrato 419/2023 (T.A. 199/2025)", "inicio": "2025-05-24", "fimVencimento": "2025-08-24", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Vicente Henrique Sansana / Rafael Antônio Gabriel", "telefone": "(41) 3381-6800"}, "anexos": [], "valor": 189202.5}'::jsonb),
('ct-imp-palmas-ubs', '{"id": "ct-imp-palmas-ubs", "cidade": "Palmas", "uf": "PR", "titulo": "Prefeitura de Palmas — UBS", "tipoServico": "Médico generalista 40h/sem (UBS) · Contrato 23/2024", "inicio": "2024-03-06", "fimVencimento": "2025-03-06", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Kosmos Panayotis Nicolaou", "telefone": "(46) 3263-7000"}, "anexos": [], "valor": 2772000.0}'::jsonb),
('ct-imp-hrnp', '{"id": "ct-imp-hrnp", "cidade": "", "uf": "PR", "titulo": "HRNP — FUNEAS — Hospital Regional do Norte Pioneiro", "tipoServico": "Serviços médicos — clínica geral e UTI Adulto III · TC 716/2025", "inicio": "2025-09-01", "fimVencimento": "2026-08-31", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Márcia C. A. Vilas Boas / Guilherme A. M. de Faria / Lukas T. de O. Lima", "telefone": "(41) 3798-5373"}, "anexos": [], "valor": 350593.92}'::jsonb),
('ct-imp-hzn', '{"id": "ct-imp-hzn", "cidade": "Londrina", "uf": "PR", "titulo": "HZN — FUNEAS — Hospital Zona Norte de Londrina", "tipoServico": "Serviços médicos — clínica geral, PS/intercorrências e internados · TC 654/2025 (1º aditivo, início futuro)", "inicio": "2026-09-01", "fimVencimento": "2027-08-31", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Naja Nabut / Fernando Cesar I. Marcucci", "telefone": "(41) 3202-6800"}, "anexos": [], "valor": 135156.36}'::jsonb),
('ct-imp-guaira', '{"id": "ct-imp-guaira", "cidade": "Guaíra", "uf": "PR", "titulo": "Guaíra — UPA 24h", "tipoServico": "Plantões médicos presenciais (UPA 24h) · Contrato 518/2025", "inicio": "2025-07-02", "fimVencimento": "2026-07-02", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Fabiano Melanias Raddatz / Luiz Rogério Carvalho", "telefone": "(44) 3642-9928", "email": "prefeitura@guaira.pr.gov.br"}, "anexos": [], "valor": 1048559.0}'::jsonb),
('ct-imp-herval', '{"id": "ct-imp-herval", "cidade": "Herval d''Oeste", "uf": "SC", "titulo": "Herval d''Oeste — UPA 24h", "tipoServico": "Plantões médicos (UPA 24h Remi Alécio Mascarello) · Contrato 088/2025", "inicio": "2025-09-01", "fimVencimento": "2026-08-31", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "João Alcides Marqueze", "telefone": "(49) 3554-0922", "email": "contratos@hervaldoeste.sc.gov.br"}, "anexos": [], "valor": 2835612.0}'::jsonb),
('ct-imp-hrl', '{"id": "ct-imp-hrl", "cidade": "", "uf": "PR", "titulo": "HRL — FUNEAS — Hospital Regional do Litoral", "tipoServico": "UTI Adulto III — plantonista diurno e noturno · TC 239/2026", "inicio": "2026-03-10", "fimVencimento": "2027-03-09", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Helio Avelar Teixeira / Rodrigo de Paula Leandro", "telefone": "(41) 3202-6800"}, "anexos": [], "valor": 52116.48}'::jsonb),
('ct-imp-palmas-upa', '{"id": "ct-imp-palmas-upa", "cidade": "Palmas", "uf": "PR", "titulo": "Palmas — UPA", "tipoServico": "Plantões médicos generalistas em escala (UPA) · Contrato 57/2026", "inicio": "2026-02-03", "fimVencimento": "2027-02-03", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Paula M. Langaro / Sylvia D. Dutra / Ducléia A. Kistemmacher", "telefone": "(46) 3263-7025"}, "anexos": [], "valor": 1405545.0}'::jsonb),
('ct-imp-antonina', '{"id": "ct-imp-antonina", "cidade": "Antonina", "uf": "PR", "titulo": "Antonina", "tipoServico": "Serviços de saúde — clínico geral por hora · Contrato 055/2026", "inicio": "2026-04-06", "fimVencimento": "2027-04-06", "modalidade": "presencial", "status": "ativo", "contato": {"nome": "Setor de Licitação", "telefone": "(41) 92000-7419", "email": "licitacao@antonina.pr.gov.br"}, "anexos": [], "valor": 107235.66}'::jsonb)
on conflict (id) do nothing;
